### ISSUE TITLE
Allow switching between Flash and HTML5 versions of the demos

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/haxeflixel.com#100]
Could have a "Flash" and a "HTML5" tab for each demo or something similar...

**Comment by impaler** [comment]
@Gama11 any idea how many demo's would work. I haven’t tried the html target in almost a year and it was far from ready then. We could add some tooling to generate everything, it would be very nice to have this for looking at the website on an ipad etc.

**Comment by Gama11** [comment]
The tooling is already there - `flixel buildprojects html5`, then just copy the html5 export folders over. ;)

I think the question is honestly rather how many demos _don't_ work at this point.

**Comment by impaler** [comment]
I've added some of the tooling. I think it needed an extra helper to move all the files to host from the `export/bin...` folders. So I've added -server to buildprojects https://github.com/HaxeFlixel/flixel-tools/commit/7445bf86a39a45fd738719956d044777bfb6cc88.

You can see them all here:
http://demos.haxeflixel.com/

To make the backgounds black I also had to override the openfl index file:
https://github.com/HaxeFlixel/flixel/commit/f2eeac03a8c716c1f41609ba4ee7ed0455a6b107

Next step will be to add a button etc to this site. Since all the demos dont work 100% http://demos.haxeflixel.com/EZPlatformer/ I am thinking we should add more meta data in the docs. Like ```target: flash, html5``` in each demo's markdown file in this repo.

**Comment by Gama11** [comment]
Nice!

Depending on how many demos (don't) work, it may be better to have something like `exclude-targets: html5`?

**Comment by DleanJeans** [comment]
Most of them don't have control support for mobile. I'll take care of them.
