### ISSUE TITLE
Leave docpad

### ISSUE THREAD

**Issue by impaler** [HaxeFlixel/haxeflixel.com#106]
The website has a very slow build time (5-15 mins) and is currently quite painful to iterate on even with the livereload. This seems to be due to the thumbnail generation and just the amount of markdown files we are generating from. This docpad setup that I even just updated, doesn't seem to cache what is already built very well.

We also have this workaround for generating the site in ./out as the site has issues generating all the thumbnails in a low memory environment like the vps it is in. Its really a bad idea to have built files like this in git and the repo is getting quite large.

Personally I think solving these issues would be time better spent in a rewrite. Docpad was initially a great solution, however this site just outgrew it. I think we can make this website more interesting and nicer to contribute to if we change the stack to something like React and Webpack.

**Comment by Gama11** [comment]
_Another_ rewrite? I was just getting somewhat comfortable with docpad. :P

It was pretty painful to work with at times, I'll give you that.. I had to run docpad in my Linux VM, since some plugin had issues on Windows and generated files with Windows-style paths with backslashes (might even have been the one for thumbnails).

Is having the generated files in Git really a docpad issue? I thought that was due to low server memory, and we could probably use some Patreon funds to upgrade that. The generated API docs are also part of flixel-docs, but that might not even be that bad since you can simply clone the repo and view the docs offline because of that...

I can't really comment on those technologies you mentioned as I don't know a lot about webdev.. Personally I've considered a rewrite with a Haxe stack (haxe.org uses ufront I think).

Also, [haxeflixel-mechanics](https://github.com/HaxeFlixel/haxeflixel-mechanics) is built with Jekyll and Bootstrap, so that's something to keep in mind (havinig a lot of different tech stacks makes things harder to manage I guess).

I think @SeiferTim would be pretty interested in this discussion.

**Comment by impaler** [comment]
Yeah another :/

So I am definitely not suggesting any change to the content (markdown files for documentation and pages), that should stay the same everywhere. Although mechanics seems to have it's own template syntax with things like {% api flixel.FlxObject %}. (a cool project this site should link with better)

I wrote the bootstrap theme for this site using the docpad livereload plugin, which is now as slow as a dog. I am wanting to do this with webpack as you get hot reload of modules https://vimeo.com/100010922 [react-hot-loader](https://github.com/gaearon/react-hot-loader). Problem is this is kind of an addictive workflow that Jekyll and docpad can't match.

React has some awesome composability and webpack lets you handle assets and custom loaders really well. I also see that both of these things have some Haxe projects that maybe worth looking into. I read somewhere massive may do a wwx talk on haxe-react.

**Comment by impaler** [comment]
I've built this again, I'll manage to make the changes I want for now, unless I get some free time to port this to something easier to maintain.
