### ISSUE TITLE
Haxeflixel.com is down

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/haxeflixel.com#205]
https://haxeflixel.com

@gamedevsam do you have any idea about the site's host or domain or anything?

**Comment by SeiferTim** [comment]
Maybe @impaler ?

**Comment by SeiferTim** [comment]
I sent an email to @impaler several hours ago.
I tried to reach out to @Beeblerox and @gamedevsam on Discord but have not heard back.

What happens if we can't get ahold of any of these people/someone who can access the domain name account?

IF/WHEN this is resolved, I think we should take some steps to try and prevent this sort of thing from happening again...
Is there a way we can set up an organization or something that is official and can have a group of like 4-5 board members who can all access all the things in case someone goes missing again?

**Comment by impaler** [comment]
I renewed the dns

**Comment by Geokureli** [comment]
Thanks!

**Comment by gamedevsam** [comment]
I'll discuss with @impaler about transferring the domain to a separate HF account and start a PW database with logins for HF gmail, Patreon, and domain registrar so we can have a succession plan.

Might take me a few weeks to get this organized since I'm on vacation in Portugal at the moment.

@SeiferTim @Geokureli @Gama11 do any of you have some thoughts about putting together a "becoming a trusted contributer" guide?

Maybe we can start a shared Google doc and detail things like how responsibilities are handed off and how we on-board people to become code contributors, and also new treasurer / lead maintainer (PS: I'm willing to keep doing the task for the foreseeable future, but to be honest I'd sleep better at night if we had these processes on place and had at least one other person with access to all the accounts).
